# Author: Hillary Mutai
#profile: https://github.com/hillarymutaik

name: airduka
description: Single page flutter app that would be deployable on both Android and IOS. 
  The app is expected to make a request to the provided API then return a list of products
  where one can be able to switch/toggle between List view and Grid View without recalling 
  the API in that process.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: any
  flutter_screenutil: ^5.0.1
  font_awesome_flutter: ^10.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  animations: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Airduka
      fonts:
        - asset: assets/fonts/Airduka.ttf
